spring:
  # 非 Web 应用程序属性文件中禁用
  main:
    web-application-type: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scms?serverTimezone=Asia/Shanghai&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource


# MYBATIS PROPERTIES
mybatis-plus:
  global-config:
    db-config:
      # 全局主键自增策略
      id-type: auto
      # 全局表前缀配置
      table-prefix: "t_"
  check-config-location: true
  # 如果xml文件在类路径下则需要添加包名 classpath*:com/demo/mybatisplus/mapper/**/*.xml 且 pom.xml 在加上 resource 配置
  # 如果xml文件在 resources 下则为 mapper/**/*.xml
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.gxjkzw.dao.entity
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
